// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mars_fit_cpp
List mars_fit_cpp(const NumericMatrix& x_in, const NumericVector& y_in, int degree, int nk, double penalty, double thresh, int minspan_in, int endspan_in, int adjust_endspan, int auto_linpreds, int nprune, int pmethod, int trace, int nthreads);
RcppExport SEXP _ares_mars_fit_cpp(SEXP x_inSEXP, SEXP y_inSEXP, SEXP degreeSEXP, SEXP nkSEXP, SEXP penaltySEXP, SEXP threshSEXP, SEXP minspan_inSEXP, SEXP endspan_inSEXP, SEXP adjust_endspanSEXP, SEXP auto_linpredsSEXP, SEXP npruneSEXP, SEXP pmethodSEXP, SEXP traceSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type minspan_in(minspan_inSEXP);
    Rcpp::traits::input_parameter< int >::type endspan_in(endspan_inSEXP);
    Rcpp::traits::input_parameter< int >::type adjust_endspan(adjust_endspanSEXP);
    Rcpp::traits::input_parameter< int >::type auto_linpreds(auto_linpredsSEXP);
    Rcpp::traits::input_parameter< int >::type nprune(npruneSEXP);
    Rcpp::traits::input_parameter< int >::type pmethod(pmethodSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_fit_cpp(x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, adjust_endspan, auto_linpreds, nprune, pmethod, trace, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// mars_basis_cpp
NumericMatrix mars_basis_cpp(const NumericMatrix& xnew, const IntegerMatrix& dirs, const NumericMatrix& cuts, const IntegerVector& selected);
RcppExport SEXP _ares_mars_basis_cpp(SEXP xnewSEXP, SEXP dirsSEXP, SEXP cutsSEXP, SEXP selectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xnew(xnewSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dirs(dirsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type cuts(cutsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type selected(selectedSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_basis_cpp(xnew, dirs, cuts, selected));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ares_mars_fit_cpp", (DL_FUNC) &_ares_mars_fit_cpp, 14},
    {"_ares_mars_basis_cpp", (DL_FUNC) &_ares_mars_basis_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ares(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
