// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mars_fit_cpp
List mars_fit_cpp(const NumericMatrix& x_in, const NumericVector& y_in, int degree, int nk, double penalty, double thresh, int minspan_in, int endspan_in, int adjust_endspan, int auto_linpreds, int fast_k, double fast_beta, int nprune, int pmethod, int trace, int nthreads, int force_size, int return_path, const Rcpp::Nullable<Rcpp::NumericVector>& weights_in, int compute_forward_qr);
RcppExport SEXP _roadrunner_mars_fit_cpp(SEXP x_inSEXP, SEXP y_inSEXP, SEXP degreeSEXP, SEXP nkSEXP, SEXP penaltySEXP, SEXP threshSEXP, SEXP minspan_inSEXP, SEXP endspan_inSEXP, SEXP adjust_endspanSEXP, SEXP auto_linpredsSEXP, SEXP fast_kSEXP, SEXP fast_betaSEXP, SEXP npruneSEXP, SEXP pmethodSEXP, SEXP traceSEXP, SEXP nthreadsSEXP, SEXP force_sizeSEXP, SEXP return_pathSEXP, SEXP weights_inSEXP, SEXP compute_forward_qrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type minspan_in(minspan_inSEXP);
    Rcpp::traits::input_parameter< int >::type endspan_in(endspan_inSEXP);
    Rcpp::traits::input_parameter< int >::type adjust_endspan(adjust_endspanSEXP);
    Rcpp::traits::input_parameter< int >::type auto_linpreds(auto_linpredsSEXP);
    Rcpp::traits::input_parameter< int >::type fast_k(fast_kSEXP);
    Rcpp::traits::input_parameter< double >::type fast_beta(fast_betaSEXP);
    Rcpp::traits::input_parameter< int >::type nprune(npruneSEXP);
    Rcpp::traits::input_parameter< int >::type pmethod(pmethodSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type force_size(force_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type return_path(return_pathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type weights_in(weights_inSEXP);
    Rcpp::traits::input_parameter< int >::type compute_forward_qr(compute_forward_qrSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_fit_cpp(x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, adjust_endspan, auto_linpreds, fast_k, fast_beta, nprune, pmethod, trace, nthreads, force_size, return_path, weights_in, compute_forward_qr));
    return rcpp_result_gen;
END_RCPP
}
// mars_basis_cpp
NumericMatrix mars_basis_cpp(const NumericMatrix& xnew, const IntegerMatrix& dirs, const NumericMatrix& cuts, const IntegerVector& selected);
RcppExport SEXP _roadrunner_mars_basis_cpp(SEXP xnewSEXP, SEXP dirsSEXP, SEXP cutsSEXP, SEXP selectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xnew(xnewSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dirs(dirsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type cuts(cutsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type selected(selectedSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_basis_cpp(xnew, dirs, cuts, selected));
    return rcpp_result_gen;
END_RCPP
}
// mars_backward_only_cpp
List mars_backward_only_cpp(const NumericMatrix& x_in, const NumericVector& y_in, const IntegerMatrix& dirs_in, const NumericMatrix& cuts_in, double penalty, int nprune, int nthreads, int force_size, int return_path, const Rcpp::Nullable<Rcpp::NumericVector>& weights_in, const Rcpp::Nullable<Rcpp::NumericMatrix>& R_in, const Rcpp::Nullable<Rcpp::NumericVector>& Qty_in);
RcppExport SEXP _roadrunner_mars_backward_only_cpp(SEXP x_inSEXP, SEXP y_inSEXP, SEXP dirs_inSEXP, SEXP cuts_inSEXP, SEXP penaltySEXP, SEXP npruneSEXP, SEXP nthreadsSEXP, SEXP force_sizeSEXP, SEXP return_pathSEXP, SEXP weights_inSEXP, SEXP R_inSEXP, SEXP Qty_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dirs_in(dirs_inSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type cuts_in(cuts_inSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int >::type nprune(npruneSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type force_size(force_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type return_path(return_pathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type weights_in(weights_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericMatrix>& >::type R_in(R_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type Qty_in(Qty_inSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_backward_only_cpp(x_in, y_in, dirs_in, cuts_in, penalty, nprune, nthreads, force_size, return_path, weights_in, R_in, Qty_in));
    return rcpp_result_gen;
END_RCPP
}
// krls_kernel_cpp
NumericMatrix krls_kernel_cpp(const NumericMatrix& X, const NumericVector& sigma_vec);
RcppExport SEXP _roadrunner_krls_kernel_cpp(SEXP XSEXP, SEXP sigma_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma_vec(sigma_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_kernel_cpp(X, sigma_vec));
    return rcpp_result_gen;
END_RCPP
}
// krls_kernel_pred_cpp
NumericMatrix krls_kernel_pred_cpp(const NumericMatrix& Xnew, const NumericMatrix& Xtrain, const NumericVector& sigma_vec);
RcppExport SEXP _roadrunner_krls_kernel_pred_cpp(SEXP XnewSEXP, SEXP XtrainSEXP, SEXP sigma_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xnew(XnewSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xtrain(XtrainSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma_vec(sigma_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_kernel_pred_cpp(Xnew, Xtrain, sigma_vec));
    return rcpp_result_gen;
END_RCPP
}
// krls_eig_cpp
List krls_eig_cpp(const arma::mat& K);
RcppExport SEXP _roadrunner_krls_eig_cpp(SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_eig_cpp(K));
    return rcpp_result_gen;
END_RCPP
}
// krls_solve_cpp
List krls_solve_cpp(const arma::vec& d, const arma::mat& V, const arma::mat& Vsq, const arma::vec& Vty, double lambda);
RcppExport SEXP _roadrunner_krls_solve_cpp(SEXP dSEXP, SEXP VSEXP, SEXP VsqSEXP, SEXP VtySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Vsq(VsqSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Vty(VtySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_solve_cpp(d, V, Vsq, Vty, lambda));
    return rcpp_result_gen;
END_RCPP
}
// krls_loo_loss_cpp
double krls_loo_loss_cpp(const arma::vec& d, const arma::mat& V, const arma::mat& Vsq, const arma::vec& Vty, double lambda);
RcppExport SEXP _roadrunner_krls_loo_loss_cpp(SEXP dSEXP, SEXP VSEXP, SEXP VsqSEXP, SEXP VtySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Vsq(VsqSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Vty(VtySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_loo_loss_cpp(d, V, Vsq, Vty, lambda));
    return rcpp_result_gen;
END_RCPP
}
// krls_gcv_loss_cpp
double krls_gcv_loss_cpp(const arma::vec& d, const arma::vec& Vty, double yty, int n_y, double lambda);
RcppExport SEXP _roadrunner_krls_gcv_loss_cpp(SEXP dSEXP, SEXP VtySEXP, SEXP ytySEXP, SEXP n_ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Vty(VtySEXP);
    Rcpp::traits::input_parameter< double >::type yty(ytySEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_gcv_loss_cpp(d, Vty, yty, n_y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// krls_deriv_cpp
arma::mat krls_deriv_cpp(const arma::mat& X, const arma::mat& K, const arma::vec& c, const arma::vec& sigma_vec);
RcppExport SEXP _roadrunner_krls_deriv_cpp(SEXP XSEXP, SEXP KSEXP, SEXP cSEXP, SEXP sigma_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_deriv_cpp(X, K, c, sigma_vec));
    return rcpp_result_gen;
END_RCPP
}
// krls_avg_deriv_var_cpp
arma::vec krls_avg_deriv_var_cpp(const arma::mat& X, const arma::mat& K, const arma::mat& V, const arma::vec& d, const arma::vec& sigma_vec, double lambda, double sigma2);
RcppExport SEXP _roadrunner_krls_avg_deriv_var_cpp(SEXP XSEXP, SEXP KSEXP, SEXP VSEXP, SEXP dSEXP, SEXP sigma_vecSEXP, SEXP lambdaSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(krls_avg_deriv_var_cpp(X, K, V, d, sigma_vec, lambda, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// krls_vsq_cpp
arma::mat krls_vsq_cpp(const arma::mat& V);
RcppExport SEXP _roadrunner_krls_vsq_cpp(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_vsq_cpp(V));
    return rcpp_result_gen;
END_RCPP
}
// krls_pairwise_sqdist_cpp
arma::mat krls_pairwise_sqdist_cpp(const arma::mat& X_a, const arma::mat& X_b);
RcppExport SEXP _roadrunner_krls_pairwise_sqdist_cpp(SEXP X_aSEXP, SEXP X_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_a(X_aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_b(X_bSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_pairwise_sqdist_cpp(X_a, X_b));
    return rcpp_result_gen;
END_RCPP
}
// krls_autotune_inner_cpp
Rcpp::List krls_autotune_inner_cpp(const arma::mat& D_tr, const arma::mat& D_te, const arma::vec& y_tr, const arma::vec& y_te, const arma::vec& sigma_grid, Rcpp::List lambda_args, int nthreads);
RcppExport SEXP _roadrunner_krls_autotune_inner_cpp(SEXP D_trSEXP, SEXP D_teSEXP, SEXP y_trSEXP, SEXP y_teSEXP, SEXP sigma_gridSEXP, SEXP lambda_argsSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D_tr(D_trSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D_te(D_teSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_tr(y_trSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_te(y_teSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_grid(sigma_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lambda_args(lambda_argsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_autotune_inner_cpp(D_tr, D_te, y_tr, y_te, sigma_grid, lambda_args, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// krls_nystrom_fit_cpp
Rcpp::List krls_nystrom_fit_cpp(const arma::mat& X_tr, const arma::mat& Z, const arma::vec& y_tr, double sigma, Rcpp::List lambda_args, double eps, bool compute_vcov);
RcppExport SEXP _roadrunner_krls_nystrom_fit_cpp(SEXP X_trSEXP, SEXP ZSEXP, SEXP y_trSEXP, SEXP sigmaSEXP, SEXP lambda_argsSEXP, SEXP epsSEXP, SEXP compute_vcovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tr(X_trSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_tr(y_trSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lambda_args(lambda_argsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_vcov(compute_vcovSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_nystrom_fit_cpp(X_tr, Z, y_tr, sigma, lambda_args, eps, compute_vcov));
    return rcpp_result_gen;
END_RCPP
}
// krls_nystrom_predict_cpp
Rcpp::NumericVector krls_nystrom_predict_cpp(const arma::mat& X_new, const arma::mat& Z, const arma::vec& alpha, double sigma);
RcppExport SEXP _roadrunner_krls_nystrom_predict_cpp(SEXP X_newSEXP, SEXP ZSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_new(X_newSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_nystrom_predict_cpp(X_new, Z, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// krls_nystrom_autotune_inner_cpp
Rcpp::List krls_nystrom_autotune_inner_cpp(const arma::mat& X_tr, const arma::mat& Z, const arma::mat& X_te, const arma::vec& y_tr, const arma::vec& y_te, const arma::vec& sigma_grid, Rcpp::List lambda_args, double eps, int nthreads);
RcppExport SEXP _roadrunner_krls_nystrom_autotune_inner_cpp(SEXP X_trSEXP, SEXP ZSEXP, SEXP X_teSEXP, SEXP y_trSEXP, SEXP y_teSEXP, SEXP sigma_gridSEXP, SEXP lambda_argsSEXP, SEXP epsSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tr(X_trSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_te(X_teSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_tr(y_trSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_te(y_teSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_grid(sigma_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lambda_args(lambda_argsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(krls_nystrom_autotune_inner_cpp(X_tr, Z, X_te, y_tr, y_te, sigma_grid, lambda_args, eps, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_roadrunner_mars_fit_cpp", (DL_FUNC) &_roadrunner_mars_fit_cpp, 20},
    {"_roadrunner_mars_basis_cpp", (DL_FUNC) &_roadrunner_mars_basis_cpp, 4},
    {"_roadrunner_mars_backward_only_cpp", (DL_FUNC) &_roadrunner_mars_backward_only_cpp, 12},
    {"_roadrunner_krls_kernel_cpp", (DL_FUNC) &_roadrunner_krls_kernel_cpp, 2},
    {"_roadrunner_krls_kernel_pred_cpp", (DL_FUNC) &_roadrunner_krls_kernel_pred_cpp, 3},
    {"_roadrunner_krls_eig_cpp", (DL_FUNC) &_roadrunner_krls_eig_cpp, 1},
    {"_roadrunner_krls_solve_cpp", (DL_FUNC) &_roadrunner_krls_solve_cpp, 5},
    {"_roadrunner_krls_loo_loss_cpp", (DL_FUNC) &_roadrunner_krls_loo_loss_cpp, 5},
    {"_roadrunner_krls_gcv_loss_cpp", (DL_FUNC) &_roadrunner_krls_gcv_loss_cpp, 5},
    {"_roadrunner_krls_deriv_cpp", (DL_FUNC) &_roadrunner_krls_deriv_cpp, 4},
    {"_roadrunner_krls_avg_deriv_var_cpp", (DL_FUNC) &_roadrunner_krls_avg_deriv_var_cpp, 7},
    {"_roadrunner_krls_vsq_cpp", (DL_FUNC) &_roadrunner_krls_vsq_cpp, 1},
    {"_roadrunner_krls_pairwise_sqdist_cpp", (DL_FUNC) &_roadrunner_krls_pairwise_sqdist_cpp, 2},
    {"_roadrunner_krls_autotune_inner_cpp", (DL_FUNC) &_roadrunner_krls_autotune_inner_cpp, 7},
    {"_roadrunner_krls_nystrom_fit_cpp", (DL_FUNC) &_roadrunner_krls_nystrom_fit_cpp, 7},
    {"_roadrunner_krls_nystrom_predict_cpp", (DL_FUNC) &_roadrunner_krls_nystrom_predict_cpp, 4},
    {"_roadrunner_krls_nystrom_autotune_inner_cpp", (DL_FUNC) &_roadrunner_krls_nystrom_autotune_inner_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_roadrunner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
