// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mars_fit_cpp
List mars_fit_cpp(const NumericMatrix& x_in, const NumericVector& y_in, int degree, int nk, double penalty, double thresh, int minspan_in, int endspan_in, int adjust_endspan, int auto_linpreds, int fast_k, double fast_beta, int nprune, int pmethod, int trace, int nthreads, int force_size, int return_path, const Rcpp::Nullable<Rcpp::NumericVector>& weights_in, int compute_forward_qr);
RcppExport SEXP _roadrunner_mars_fit_cpp(SEXP x_inSEXP, SEXP y_inSEXP, SEXP degreeSEXP, SEXP nkSEXP, SEXP penaltySEXP, SEXP threshSEXP, SEXP minspan_inSEXP, SEXP endspan_inSEXP, SEXP adjust_endspanSEXP, SEXP auto_linpredsSEXP, SEXP fast_kSEXP, SEXP fast_betaSEXP, SEXP npruneSEXP, SEXP pmethodSEXP, SEXP traceSEXP, SEXP nthreadsSEXP, SEXP force_sizeSEXP, SEXP return_pathSEXP, SEXP weights_inSEXP, SEXP compute_forward_qrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< int >::type nk(nkSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type minspan_in(minspan_inSEXP);
    Rcpp::traits::input_parameter< int >::type endspan_in(endspan_inSEXP);
    Rcpp::traits::input_parameter< int >::type adjust_endspan(adjust_endspanSEXP);
    Rcpp::traits::input_parameter< int >::type auto_linpreds(auto_linpredsSEXP);
    Rcpp::traits::input_parameter< int >::type fast_k(fast_kSEXP);
    Rcpp::traits::input_parameter< double >::type fast_beta(fast_betaSEXP);
    Rcpp::traits::input_parameter< int >::type nprune(npruneSEXP);
    Rcpp::traits::input_parameter< int >::type pmethod(pmethodSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type force_size(force_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type return_path(return_pathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type weights_in(weights_inSEXP);
    Rcpp::traits::input_parameter< int >::type compute_forward_qr(compute_forward_qrSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_fit_cpp(x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, adjust_endspan, auto_linpreds, fast_k, fast_beta, nprune, pmethod, trace, nthreads, force_size, return_path, weights_in, compute_forward_qr));
    return rcpp_result_gen;
END_RCPP
}
// mars_basis_cpp
NumericMatrix mars_basis_cpp(const NumericMatrix& xnew, const IntegerMatrix& dirs, const NumericMatrix& cuts, const IntegerVector& selected);
RcppExport SEXP _roadrunner_mars_basis_cpp(SEXP xnewSEXP, SEXP dirsSEXP, SEXP cutsSEXP, SEXP selectedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xnew(xnewSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dirs(dirsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type cuts(cutsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type selected(selectedSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_basis_cpp(xnew, dirs, cuts, selected));
    return rcpp_result_gen;
END_RCPP
}
// mars_backward_only_cpp
List mars_backward_only_cpp(const NumericMatrix& x_in, const NumericVector& y_in, const IntegerMatrix& dirs_in, const NumericMatrix& cuts_in, double penalty, int nprune, int nthreads, int force_size, int return_path, const Rcpp::Nullable<Rcpp::NumericVector>& weights_in, const Rcpp::Nullable<Rcpp::NumericMatrix>& R_in, const Rcpp::Nullable<Rcpp::NumericVector>& Qty_in);
RcppExport SEXP _roadrunner_mars_backward_only_cpp(SEXP x_inSEXP, SEXP y_inSEXP, SEXP dirs_inSEXP, SEXP cuts_inSEXP, SEXP penaltySEXP, SEXP npruneSEXP, SEXP nthreadsSEXP, SEXP force_sizeSEXP, SEXP return_pathSEXP, SEXP weights_inSEXP, SEXP R_inSEXP, SEXP Qty_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dirs_in(dirs_inSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type cuts_in(cuts_inSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< int >::type nprune(npruneSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type force_size(force_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type return_path(return_pathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type weights_in(weights_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericMatrix>& >::type R_in(R_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type Qty_in(Qty_inSEXP);
    rcpp_result_gen = Rcpp::wrap(mars_backward_only_cpp(x_in, y_in, dirs_in, cuts_in, penalty, nprune, nthreads, force_size, return_path, weights_in, R_in, Qty_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_roadrunner_mars_fit_cpp", (DL_FUNC) &_roadrunner_mars_fit_cpp, 20},
    {"_roadrunner_mars_basis_cpp", (DL_FUNC) &_roadrunner_mars_basis_cpp, 4},
    {"_roadrunner_mars_backward_only_cpp", (DL_FUNC) &_roadrunner_mars_backward_only_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_roadrunner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
