# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mars_fit_cpp <- function(x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, adjust_endspan, auto_linpreds, fast_k, fast_beta, nprune, pmethod, trace, nthreads, force_size, return_path, weights_in = NULL, compute_forward_qr = 0L) {
    .Call(`_roadrunner_mars_fit_cpp`, x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, adjust_endspan, auto_linpreds, fast_k, fast_beta, nprune, pmethod, trace, nthreads, force_size, return_path, weights_in, compute_forward_qr)
}

mars_basis_cpp <- function(xnew, dirs, cuts, selected) {
    .Call(`_roadrunner_mars_basis_cpp`, xnew, dirs, cuts, selected)
}

mars_backward_only_cpp <- function(x_in, y_in, dirs_in, cuts_in, penalty, nprune, nthreads, force_size, return_path, weights_in = NULL, R_in = NULL, Qty_in = NULL) {
    .Call(`_roadrunner_mars_backward_only_cpp`, x_in, y_in, dirs_in, cuts_in, penalty, nprune, nthreads, force_size, return_path, weights_in, R_in, Qty_in)
}

krls_kernel_cpp <- function(X, sigma_vec, kernel_type = 0L, kernel_c = 1.0) {
    .Call(`_roadrunner_krls_kernel_cpp`, X, sigma_vec, kernel_type, kernel_c)
}

krls_kernel_pred_cpp <- function(Xnew, Xtrain, sigma_vec, kernel_type = 0L, kernel_c = 1.0) {
    .Call(`_roadrunner_krls_kernel_pred_cpp`, Xnew, Xtrain, sigma_vec, kernel_type, kernel_c)
}

krls_eig_cpp <- function(K) {
    .Call(`_roadrunner_krls_eig_cpp`, K)
}

krls_solve_cpp <- function(d, V, Vsq, Vty, lambda) {
    .Call(`_roadrunner_krls_solve_cpp`, d, V, Vsq, Vty, lambda)
}

krls_loo_loss_cpp <- function(d, V, Vsq, Vty, lambda) {
    .Call(`_roadrunner_krls_loo_loss_cpp`, d, V, Vsq, Vty, lambda)
}

krls_gcv_loss_cpp <- function(d, Vty, yty, n_y, lambda) {
    .Call(`_roadrunner_krls_gcv_loss_cpp`, d, Vty, yty, n_y, lambda)
}

krls_deriv_cpp <- function(X, K, c, sigma_vec, kernel_type = 0L, kernel_c = 1.0) {
    .Call(`_roadrunner_krls_deriv_cpp`, X, K, c, sigma_vec, kernel_type, kernel_c)
}

krls_avg_deriv_var_cpp <- function(X, K, V, d, sigma_vec, lambda, sigma2, kernel_type = 0L, kernel_c = 1.0) {
    .Call(`_roadrunner_krls_avg_deriv_var_cpp`, X, K, V, d, sigma_vec, lambda, sigma2, kernel_type, kernel_c)
}

krls_vsq_cpp <- function(V) {
    .Call(`_roadrunner_krls_vsq_cpp`, V)
}

krls_posterior_var_cpp <- function(Xnew, Xtr, V, d, lambda, kernel_type, sigma_vec, kernel_c) {
    .Call(`_roadrunner_krls_posterior_var_cpp`, Xnew, Xtr, V, d, lambda, kernel_type, sigma_vec, kernel_c)
}

krls_pairwise_sqdist_cpp <- function(X_a, X_b) {
    .Call(`_roadrunner_krls_pairwise_sqdist_cpp`, X_a, X_b)
}

krls_autotune_inner_cpp <- function(D_tr, D_te, y_tr, y_te, sigma_grid, lambda_args, nthreads) {
    .Call(`_roadrunner_krls_autotune_inner_cpp`, D_tr, D_te, y_tr, y_te, sigma_grid, lambda_args, nthreads)
}

krls_nystrom_fit_cpp <- function(X_tr, Z, y_tr, sigma, lambda_args, eps, compute_vcov) {
    .Call(`_roadrunner_krls_nystrom_fit_cpp`, X_tr, Z, y_tr, sigma, lambda_args, eps, compute_vcov)
}

krls_nystrom_predict_cpp <- function(X_new, Z, alpha, sigma) {
    .Call(`_roadrunner_krls_nystrom_predict_cpp`, X_new, Z, alpha, sigma)
}

krls_nystrom_autotune_inner_cpp <- function(X_tr, Z, X_te, y_tr, y_te, sigma_grid, lambda_args, eps, nthreads) {
    .Call(`_roadrunner_krls_nystrom_autotune_inner_cpp`, X_tr, Z, X_te, y_tr, y_te, sigma_grid, lambda_args, eps, nthreads)
}

krls_irls_logistic_cpp <- function(K, y, lambda, w_obs = NULL, tol = 1e-6, max_iter = 50L, max_halve = 5L, trace = 0L) {
    .Call(`_roadrunner_krls_irls_logistic_cpp`, K, y, lambda, w_obs, tol, max_iter, max_halve, trace)
}

krls_logistic_loo_loss_cpp <- function(eta, y, p, W, H_diag) {
    .Call(`_roadrunner_krls_logistic_loo_loss_cpp`, eta, y, p, W, H_diag)
}

plda_wcsd_cpp <- function(x, y, G) {
    .Call(`_roadrunner_plda_wcsd_cpp`, x, y, G)
}

plda_softthresh_cpp <- function(u, lam) {
    .Call(`_roadrunner_plda_softthresh_cpp`, u, lam)
}

plda_tv1d_cpp <- function(u, lam) {
    .Call(`_roadrunner_plda_tv1d_cpp`, u, lam)
}

plda_fit_cpp <- function(x, y, G, K, lambda, lambda2, penalty, maxit, tol) {
    .Call(`_roadrunner_plda_fit_cpp`, x, y, G, K, lambda, lambda2, penalty, maxit, tol)
}

plda_project_cpp <- function(xnew, mu, sdw, discrim) {
    .Call(`_roadrunner_plda_project_cpp`, xnew, mu, sdw, discrim)
}

