# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mars_fit_cpp <- function(x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, nprune, pmethod, trace, nthreads) {
    .Call(`_ares_mars_fit_cpp`, x_in, y_in, degree, nk, penalty, thresh, minspan_in, endspan_in, nprune, pmethod, trace, nthreads)
}

mars_basis_cpp <- function(xnew, dirs, cuts, selected) {
    .Call(`_ares_mars_basis_cpp`, xnew, dirs, cuts, selected)
}

